// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gameProto.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Protos {
  public static partial class GameService
  {
    static readonly string __ServiceName = "gameProto.GameService";

    static readonly grpc::Marshaller<global::Protos.Settings> __Marshaller_gameProto_Settings = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protos.Settings.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protos.SettingsResponse> __Marshaller_gameProto_SettingsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protos.SettingsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protos.ClearMessage> __Marshaller_gameProto_ClearMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protos.ClearMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protos.Frame> __Marshaller_gameProto_Frame = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protos.Frame.Parser.ParseFrom);

    static readonly grpc::Method<global::Protos.Settings, global::Protos.SettingsResponse> __Method_SettingApplication = new grpc::Method<global::Protos.Settings, global::Protos.SettingsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SettingApplication",
        __Marshaller_gameProto_Settings,
        __Marshaller_gameProto_SettingsResponse);

    static readonly grpc::Method<global::Protos.ClearMessage, global::Protos.Frame> __Method_StartGame = new grpc::Method<global::Protos.ClearMessage, global::Protos.Frame>(
        grpc::MethodType.Unary,
        __ServiceName,
        "StartGame",
        __Marshaller_gameProto_ClearMessage,
        __Marshaller_gameProto_Frame);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Protos.GameProtoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GameService</summary>
    [grpc::BindServiceMethod(typeof(GameService), "BindService")]
    public abstract partial class GameServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Protos.SettingsResponse> SettingApplication(global::Protos.Settings request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Protos.Frame> StartGame(global::Protos.ClearMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GameService</summary>
    public partial class GameServiceClient : grpc::ClientBase<GameServiceClient>
    {
      /// <summary>Creates a new client for GameService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GameServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GameService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GameServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GameServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GameServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Protos.SettingsResponse SettingApplication(global::Protos.Settings request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SettingApplication(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Protos.SettingsResponse SettingApplication(global::Protos.Settings request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SettingApplication, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Protos.SettingsResponse> SettingApplicationAsync(global::Protos.Settings request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SettingApplicationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Protos.SettingsResponse> SettingApplicationAsync(global::Protos.Settings request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SettingApplication, null, options, request);
      }
      public virtual global::Protos.Frame StartGame(global::Protos.ClearMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartGame(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Protos.Frame StartGame(global::Protos.ClearMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StartGame, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Protos.Frame> StartGameAsync(global::Protos.ClearMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StartGameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Protos.Frame> StartGameAsync(global::Protos.ClearMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StartGame, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GameServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GameServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GameServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SettingApplication, serviceImpl.SettingApplication)
          .AddMethod(__Method_StartGame, serviceImpl.StartGame).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GameServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SettingApplication, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protos.Settings, global::Protos.SettingsResponse>(serviceImpl.SettingApplication));
      serviceBinder.AddMethod(__Method_StartGame, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protos.ClearMessage, global::Protos.Frame>(serviceImpl.StartGame));
    }

  }
}
#endregion
